services:
  backend:
    build: .
    container_name: banksproject-app
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: banksproject-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - app-network

# Descomenta esto si en el futuro quieres migrar de H2 a Postgres:
#  db:
#    image: postgres:16-alpine
#    container_name: banksproject-db
#    restart: always
#    environment:
#      POSTGRES_DB: banks_db
#      POSTGRES_USER: bank_user
#      POSTGRES_PASSWORD: bank_password
#    volumes:
#      - db_data:/var/lib/postgresql/data
#    networks:
#      - app-network

# volumes:
#   db_data:

networks:
  app-network:
    driver: bridge