CREATE TABLE enduser(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    api_key VARCHAR(255) NOT NULL
);

CREATE TABLE bank(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    bank_code VARCHAR(255),
    url VARCHAR(500),
    owner_id INTEGER,
    FOREIGN KEY (owner_id) REFERENCES enduser(id) ON DELETE CASCADE
);

CREATE TABLE mortgage(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id INTEGER NOT NULL,
    name VARCHAR(255),
    type VARCHAR(50),
    description VARCHAR(500),
    TAE decimal(10,2)
);

CREATE TABLE mortgage_favorite (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER NOT NULL,
    mortgage_id INTEGER NOT NULL,
    FOREIGN KEY (user_id)     REFERENCES enduser(id)  ON DELETE CASCADE,
    FOREIGN KEY (mortgage_id) REFERENCES mortgage(id) ON DELETE CASCADE,
    CONSTRAINT uq_user_mortgage UNIQUE (user_id, mortgage_id)
);
